name: CI/CD for Strapi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Enable corepack
      run: corepack enable
    
    - name: Install npm version that supports workspaces
      run: corepack prepare npm@8.1.0 --activate
    
    - name: Install dependencies
      run: npm install
    
    - name: Build Strapi
      run: npm run build
    
    - name: Run tests (if applicable)
      run: npm test

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /path/to/your/strapi/app
          git pull
          npm install
          npm run build
          pm2 restart strapi || pm2 start npm --name "strapi" -- start
