name: CI/CD for Strapi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Upgrade npm
      run: npm install -g npm@latest

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Ensure PM2 is installed
          if ! command -v pm2 &> /dev/null
          then
              echo "PM2 could not be found, installing."
              sudo npm install -g pm2
          fi

          # Clone or pull the latest code from the Strapi repository
          if [ ! -d "strapi_pearlthoughts_2" ]; then
            git clone https://github.com/Deepak2202-del/strapi_pearlthoughts_2.git
          else
            cd strapi_pearlthoughts_2
            git pull
            cd ..
          fi

          # Change directory to the Strapi project
          cd strapi_pearlthoughts_2

          # Install project dependencies
          npm install

          # Build the Strapi application
          npm run build

          # Stop any existing PM2 process with the name "strapi"
          pm2 delete strapi || true

          # Start the Strapi application with PM2 and name it "strapi"
          pm2 start npm --name "strapi" -- run start

          # Save PM2 process list and enable startup on reboot
          pm2 save
          pm2 startup

          # Print a message indicating success
          echo "Strapi has been deployed and started successfully."

    - name: Notify Success
      if: success()
      run: echo "Deployment completed successfully!"

    - name: Notify Failure
      if: failure()
      run: echo "Deployment failed!"
