name: CI/CD for Strapi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Ensure compatibility with your project

    - name: Upgrade npm
      run: npm install -g npm@latest

    - name: Install dependencies
      run: npm install strapi@beta -g

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          
          # Define the path to your Strapi app
          APP_PATH="/home/ubuntu/strapi-app"

          # Check if the directory exists
          if [ ! -d "$APP_PATH" ]; then
            echo "Directory $APP_PATH does not exist."
            exit 1
          fi

          # Navigate to your Strapi app directory
          cd $APP_PATH

          # Check if package.json exists
          if [ ! -f "package.json" ]; then
            echo "package.json not found in $APP_PATH"
            exit 1
          fi

          # Pull the latest changes from Git
          git pull

          # Install dependencies
          npm install

          # Build the Strapi app
          npm run build

          # Restart or start the Strapi app with pm2
          pm2 restart strapi || pm2 start npm --name "strapi" -- start
          
