name: CI/CD for Strapi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify the version of Node.js you need

    - name: Upgrade npm
      run: npm install -g npm@latest

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install strapi@beta -g

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Ensure Node.js and npm are available
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
          nvm install 18
          nvm use 18

          # Navigate to your Strapi app directory
          cd /actual/path/to/your/strapi/app

          # Pull the latest changes from Git
          git pull

          # Install dependencies
          npm install

          # Build the Strapi app
          npm run build

          # Restart or start the Strapi app with pm2
          pm2 restart strapi || pm2 start npm --name "strapi" -- start
